### ISSUE TITLE
Question about "--with-registry-auth"

### ISSUE THREAD

**Issue by pascalandy** [jakubhajek/traefik-consul-swarm#2]
As I use docker hub, do I need to pass this attribute?

Thanks!

**Comment by jakubhajek** [comment]
Hi @pascalandy, 

The attribute `--with-registry-auth` is required if you use a private repo which is password protected. First, you need to execute command `docker login` on one of the manager nodes which a member of the Docker Swarm cluster.  If you use public repo, you don't need to pass this attribute.
